== Vector Tiles Extension (Normative)

=== Extension Title

Vector Tiles

=== Introduction

The GeoPackage Vector Tiles extension defines the rules and requirements for encoding vector tiles in a GeoPackage data store<<1>>. 
It is based on the https://www.mapbox.com/vector-tiles/specification/[Mapbox Vector Tiles (MVT) specification] https://github.com/mapbox/vector-tile-spec/tree/master/2.1[version 2.1]
and uses https://github.com/google/protobuf[Google Protocol Buffers] as the content encoding for each tile.

This extension, like all GeoPackage extensions, is intended to be transparent and to not interfere with GPKG compliant, but non-supporting, software packages.

=== Extension Author

Image Matters LLC

=== Extension Name or Template

`im_vector_tiles` (If this extension is adopted by OGC, then `gpkg_vector_tiles` will be named as an alias.)

=== Extension Type

This extension provides new requirements dependent on GeoPackage http://www.geopackage.org/spec120/index.html#tiles[Clause 2.2].

=== Applicability

This extension defines an alternate way to encode feature information into a GeoPackage.

=== Scope

read-write

=== Specification

If this extension is in use, then all of the http://www.geopackage.org/guidance/getting-started.html#tiles[Tiles Option] applies.
There are two additional required metadata tables, <<gpkgext_vt_layers>> and <<gpkgext_vt_fields>>, that mirror the attributes structure from MVT. 
This allows client software to understand the feature schemas without having to open individual tiles.

==== `gpkg_extensions`
To use this extension, add the following rows to this table.

| *table_name* | *column_name* | *extension_name* | *definition* | *scope* |
| ------------ | ------------- | ---------------- | ------------ | ------- |
| `gpkgext_vt_layers`   | NULL  | `im_vector_tiles`   | https://github.com/jyutzler/geopackage-vector-tiles/blob/master/spec/1_vector_tiles.adoc | _read-write_  |
| `gpkgext_vt_fields`   | NULL  | `im_vector_tiles`   | https://github.com/jyutzler/geopackage-vector-tiles/blob/master/spec/1_vector_tiles.adoc | _read-write_  |
| _tile pyramid user data table name_   | `tile_data`  | `im_vector_tiles`   | https://github.com/jyutzler/geopackage-vector-tiles/blob/master/spec/1_vector_tiles.adoc | _read-write_  |

==== User Data Tables
Like other tile-based content, the physical data is stored in http://www.geopackage.org/guidance/getting-started.html#user-data-tables[user-defined tiles tables].
The `tile_data` is a Google Protocol Buffer as https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto[defined by MVT].

Unless you use an extension, PNG and JPG are the two supported file types for the tiles. 
PNG is generally better for synthetic data (i.e., digital maps) because it is lossless and its compression codec compresses synthetic data fairly well. 
JPG is generally better for natural data (i.e., satellite or aerial imagery) due to its superior (though lossy) compression. 
However, since PNG supports alpha transparency and JPG does not, it is common to use PNG tiles around the boundary of a tile pyramid. 
This allows users to see the data underneath the tile boundaries. 
JPG files have an adjustable compression rating. 
We have found that a ratings in the range 50-75 (out of 100) work best for imagery. 
Ratings that are too high use too much space and ratings that are too low have too many visible artifacts. 
Within the 50-75 range it is a reasonable tradeoff between file size and image quality.

Tile pyramids may be sparsely populated. 
This is a good way to manage GeoPackage size. 
Applications should be aware of this possibility and if possible, drop to the next zoom level to render that part of the map. 






==== Table Definitions
[[gpkgext_vt_layers]]
===== Tiles
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL support >.
====

===== Layers
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkgext_vt_layers` table as per <<gpkgext_vt_layers_table>> and <<gpkgext_vt_layers_sql>>.
====

[[gpkgext_vt_layers_table]]
.Vector Tiles Layers Table Definition
[cols="10,5,40,5,5,5,5",options="header",]
|=======================================================================
|Column Name            |Column Type  |Column Description               |Null |Default  |Key |Unique
|`id`                   |TEXT         |Layer name (see note below)      |no   |         |PK  |yes
|`table_name`           |TEXT         |Name of user-defined tiles table |no   |         |    |jointly with `layer_name`
|`layer_name`           |TEXT         |Layer name                       |no   |         |    |jointly with `table_name`
|`minzoom`              |INTEGER      |Minimum zoom level               |no   |         |    |no
|`maxzoom`              |INTEGER      |Maximum zoom level               |no   |         |    |no
|=======================================================================

===== Fields
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkgext_vt_fields` table as per <<gpkgext_vt_fields_table>> and <<gpkgext_vt_fields_sql>>.
====

[[gpkgext_vt_fields_table]]
.Vector Tiles Fields Table Definition
[cols="10,5,40,5,5,5,5",options="header",]
|=======================================================================
|Column Name            |Column Type  |Column Description         |Null |Default  |Key |Unique
|`id`                   |INTEGER      |Autoincrement primary key  |no   |         |PK  |yes
|`layer_id`             |TEXT         |Layer ID                   |no   |         |FK  |yes
|`name`                 |TEXT         |Field Name                 |no   |         |    |no
|`type`                 |TEXT         |'String' or 'Number'       |no   |         |    |no
|=======================================================================

==== Table Values
===== `gpkg_extensions`
[[r8]]
[caption=""]
.Requirement 8
====
A GeoPackage that complies with the Related Tables extension SHALL contain rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>. There SHALL be a row for `gpkgext_relations`.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|table_name|column_name|extension_name|definition|scope
|`gpkgext_vt_layers`|null|`im_vector_tiles`|TBD|`read-write`
|`gpkgext_vt_fields`|null|`im_vector_tiles`|TBD|`read-write`
|_name of actual vector tiles table_|null|`im_vector_tiles`|TBD|`read-write`
|=======================================================================

===== Layers
[[r9]]
[caption=""]
.Requirement 9
====
For each `table_name` column value in `gpkgext_vt_layers`, there SHALL be a table or view of the name referenced in `primary_table_name` and that table SHALL have an entry in `gpkg_contents`.
====

[[r10]]
[caption=""]
.Requirement 10
====
For each row in `gpkgext_relations`, there SHALL be a table or view of the name specified in `attribute_table_name`. This attributes table SHALL have an entry in `gpkg_contents` with a `data_type` of 'attributes'. The attribute table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.
====

[NOTE]
====
The `cardinality` column is informational only. It should be populated during the data load process and updated by the GeoPackage client if needed. Export processes may use this column to determine the right way to export the data.
====

====== Example

This example illustrates support for many-to-many relationships but the concept may be used in a degenerative way to support one-to-many or many-to-one relationships.
The content of the `gpkgext_relations` includes a <<features_to_media>> that relates the <<features>> and <<media>> using their respective `id` columns.

In this example, there are four features (ID 1, 2, 3 and 4) and three PNG media items (ID 17, 18, and 19).
Using the <<features_to_media>>,

 * feature 1 relates to media 17 and 18
 * feature 2 relates to media 18
 * feature 3 relates to media 18
 * feature 4 relates to media 17 and 19

.gpkgext_relations table values
[options="header"]
|==============================================
|primary_table_name|primary_column|attribute_table_name|attribute_column|relation_name|mapping_table|cardinality
|features          |id            |media               |id              |media        |features_to_media|many-to-many
|==============================================

[[features]]
.features table values
[width="50%",options="header"]
|=======================================================================
|id|geom
|1|<BLOB>
|2|<BLOB>
|3|<BLOB>
|4|<BLOB>
|=======================================================================

[[media]]
.media table values
[width="80%",options="header"]
|=======================================================================
|id|data|content_type
|17|<BLOB>|image/png
|18|<BLOB>|image/png
|19|<BLOB>|image/png
|=======================================================================

[[features_to_media]]
.features_to_media table
[options="header"]
|==============================================
|primary_column_value|attribute_column_value
|4  | 17
|4  | 19
|3  | 18
|2  | 18
|1  | 18
|1  | 17
|==============================================

The <<features_to_media>> relates the id columns between the features table and the media table.


=== Table Definition SQL

[[gpkgext_relations_sql]]
.Extended Relations Table Definition SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'gpkgext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_table_name TEXT NOT NULL,
  primary_column TEXT NOT NULL,
  foreign_table_name TEXT NOT NULL,
  foreign_column TEXT NOT NULL,
  relation_name TEXT NOT NULL,
  mapping_table TEXT UNIQUE,
  cardinality TEXT NOT NULL
 );
----

[[gpkgext_user_defined_mapping_table_sql]]
.Extended Relations Mapping Table SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_mapping_table' (
  primary_column_id INTEGER NOT NULL,
  attribute_column_id INTEGER NOT NULL
 );
----

[[gpkg_features_sql]]
.Example User Defined Features Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_feature_table' (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  geometry GEOMETRY,
  text_attribute TEXT,
  real_attribute REAL,
  boolean_attribute BOOLEAN,
  relation TEXT NULL);
----
This table is a modified version of http://www.geopackage.org/spec/#_sample_feature_table_informative[the informative example in the core document].

[[gpkg_extensions_sql]]
.Example User Defined Media Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_media' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data BLOB NOT NULL,
  content_type TEXT NOT NULL,
  relation TEXT NULL);
----

=== Abstract Test Suite (Normative)
TBD

=== References

==== Normative References

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
However, parties to agreements based on this part of this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below.
For undated references, the latest edition of the normative document referenced applies.

[bibliography]
- [[[1]]] http://www.geopackage.org/spec120/index.html[OGC 12-128r14 OGC® GeoPackage Encoding Standard v1.2.0 (On-line)]
- [[[2]]] TBD

== Graveyard

=====

===== User Defined Mapping Tables
[[r4]]
[caption=""]
.Requirement 4
====
A GeoPackage that complies with this extension SHALL contain a mapping table for each distinct value in the `mapping_table` column of the `gpkgext_relations_table` as per  <<gpkgext_user_defined_mapping_table>>.

[[r5]]
[caption=""]
.Requirement 5
====
A mapping table MAY contain no rows. Each row that is present SHALL map a row of a feature/attribute/tile table to a row of the attribute table. The two columns SHALL be used to map between the core data table using the `primary_column_id` and the attribute table using the `attribute_column_id`.

[[r6]]
[caption=""]
.Requirement 6
====
The two columns of a mapping table SHALL be used to map between the core data table using the `primary_column_id` and the attribute table using the `attribute_column_id`.
====
[[gpkgext_user_defined_mapping_table]]
.User Defined Mapping Table Definition
[cols=",,,,,,",options="header",]

|=================================================================
|Column Name           | Column Type | Column Description                                     |Null |Default  |Key |Unique
|`primary_column_id`   | INTEGER     | Name of the primary key column in the primary table    |no   |         |    |no
|`attribute_column_id` | INTEGER     | Name of the primary key column in the attribute table  |no   |         |    |no
|=================================================================

===== User Defined Attributes (Media) Tables
[[r7]]
[caption=""]
.Requirement 7
====
A GeoPackage that complies with this extension SHALL contain one or more user-defined attribute (media) tables or views as per <<gpkg_user_defined_media_table>>. These tables MAY contain other columns.
====

[[gpkg_user_defined_media_table]]
.User Defined Media Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name    |Column Type |Column Description        |Null |Key
|`id`           |INTEGER     |Autoincrement primary key |no   |PK
|`data`         |BLOB        |Multimedia content        |no   |
|`content_type` |TEXT        |Mime-type of data         |no   |
|=======================================================================

