[[owscontext_extension]]
=== GeoPackage OWS Context Extension

[WARNING]
====
This subsection is under discussion and may change radically.
====

==== Extension Title

OWS Context

==== Introduction

This extension provides a mechanism for storing http://owscontext.org[OWS Context] content in a GeoPackage using the standard link:https://portal.opengeospatial.org/files/?artifact_id=55183[ATOM] or link:https://portal.opengeospatial.org/files/?artifact_id=68826[GeoJSON] encoding.

==== Extension Author

Image Matters LLC, in collaboration with the participants of the OGC Vector Tiles Pilot and the OWS Context SWG.

==== Extension Name or Template

`im_ows_context` (will become `gpkg_ows_context` if adopted by OGC)

==== Extension Type

New requirement dependent on http://www.geopackage.org/spec/#core[GeoPackage Core (Clause 1)].

==== Applicability

This extension adds an additional level of organization to existing GeoPackage data.

==== Scope

read-write

==== Specification
===== `gpkg_extensions`

To use this extension, add the following row to this table.

[[ows_context_ger_table]]
.gpkg_extensions Table Rows
[cols=",,,,",options="header",]
|========================================================================================================================================================================
| table_name | column_name | extension_name | definition | scope
|`gpkgext_contexts` |null |`im_ows_context` |_a reference to this file_ |`read-write`
|========================================================================================================================================================================

[NOTE]
==========
The values in the `definition` column SHOULD refer in some human-readable way to this extension specification. If the extension is adopted by OGC, it will gain the "gpkg_" prefix and get a different definition permalink.
==========

[[gpkgext_contexts]]
===== `gpkgext_contexts`
This table describes OWS Context instances. 
The columns of this table are:

* `id` is a primary key
* `name` is a text label for the context
* `format` is the format of the context (e.g., `atom` or `geojson`)
* `context` is the actual context text
* `title` is an optional text title designed to be human-readable
* `description` is an optional text description designed to be human-readable
